let outText = "";
async function generatePDB() {
  const naType = (naTypeEl.value === 'RNA') ? 'RNA' : 'DNA';
  _CURRENT_NA_TYPE = naType;
  const N = Math.max(1, Math.min(4, parseInt(numLayersEl.value || "1")));
  const layerTpls = getLayersArray();
  const rises  = Array.from(document.querySelectorAll(".gapRise")).map(inp => parseFloat(inp.value || "0"));
  const twists = Array.from(document.querySelectorAll(".gapTwist")).map(inp => parseFloat(inp.value || "0"));
  const handGlobal = (globalHandEl.value || 'right');
  const topology = topologyEl?.value || 'parallel';
  const perLayerTemplates = await Promise.all(
    Array.from({length:N}, async (_,i)=>{
      const sense = (layerTpls[i] === 'acw') ? 'ACW' : 'CW';
      return fetchTemplateForLayer(naType, handGlobal, topology, i+1, sense);
    })
  );
  let serial = 1, cumZ = 0.0, cumDeg = 0.0;
  const atomsOut = [];
  const header = [];
  header.push("HEADER    4MRNA-G4 MODEL");
  header.push(`REMARK   4 Generated by 4MRNA-G4 web app`);
  header.push(`REMARK   5 NA_TYPE=${naType}  LAYERS=${N}  GLOBAL_HAND=${handGlobal}`);
  header.push(`REMARK   6 TOPOLOGY=${topology}`);
  header.push(`REMARK   7 PIPELINE=Place(Rise/Twist) → PO-fit×2 (glyco→C5→O5, each 2-pass) → BackboneMin(strong: bonds+angles+weak dihedral) → ClashResolve → torsionalRepulsionFinal → Final-LSQ(bonds + angles(0.5) + O3'-P)`);
  for (let i = 0; i < N; i++) {
    const raw = perLayerTemplates[i].atoms;
    const layerPlaced = [];
    if (i > 0) {
      const rise  = rises[i - 1] || 0;
      const signedTwist = twists[i - 1] || 0;
      cumZ   += -rise;
      cumDeg += -signedTwist;
    }
    for (const a0 of raw) {
      const p  = { x: a0.x, y: a0.y, z: a0.z + cumZ };
      let newResName = a0.resName;
      if (naType === 'RNA' && a0.resName && a0.resName.trim() === "DG") newResName = "G";
      const chainID = a0.chainID || 'A';
      const resSeqLayer = resSeqForChain(i, N, chainID, topology);
      layerPlaced.push({
        ...a0,
        x: p.x, y: p.y, z: p.z,
        resSeq: resSeqLayer,
        serial: serial++,
        resName: newResName
      });
    }
    if (cumDeg !== 0) {
      const m = meanC1pXYZ(layerPlaced);
      const originZ = { x: 0, y: 0, z: m ? m.z : 0 };
      const zAxis   = { x: 0, y: 0, z: 1 };
      rotateAtomsAroundAxis(layerPlaced, originZ, zAxis, cumDeg * Math.PI/180);
    }
    atomsOut.push(...layerPlaced);
  }
  runPOFitAllChains(atomsOut);                                    
  runPOFitAllChains(atomsOut);                                 
  minimizeBackbone(atomsOut, {maxIter: 800, gtol: 1e-6, alpha0: 0.2});
  resolveClashesLocal(atomsOut, {
  cutoff: 4.5, scaleS: 0.90, betaNeighbor: 0.25, iters: 10, maxShiftPerIter: 0.25
}); 
  for (let cycle = 0; cycle < 3; cycle++) {
    torsionalRepulsionFinal(atomsOut, {
      cutOP: 2.6, cutPC: 3.0, maxIter: 12, stepDegTors: 2.0, stepDegAngle: 1.0
    });
    minimizeBackboneFinalLSQ(atomsOut, {
      maxIter: 400, gtol: 1e-6, alpha0: 0.18, wAngle: 0.5, wPO: 2.0
    });
    enforceTetrahedralAroundP(atomsOut, { targetDeg:109.5, stepDeg:0.5, iters:1 });
  }
  const lines = [...header, ...atomsOut.map(formatAtom), "END"];
  return lines.join("\n");
}
document.addEventListener('DOMContentLoaded', async ()=>{
  const clamp = ()=>{ if(parseInt(numLayersEl.value||'4') > 4) numLayersEl.value = '4'; };
  clamp();
  numLayersEl.addEventListener('change', ()=>{ clamp(); buildControls(); });
  globalHandEl.addEventListener('change', refreshDefaultsFromGlobal);
  topologyEl?.addEventListener('change', onTopologyChange);
  naTypeEl?.addEventListener('change', ()=>{});
  buildControls();
  ensureViewer();
  setTimeout(()=>{ try{ viewer.resize(); }catch(_){} }, 0);
});
document.getElementById("generateBtn").addEventListener("click", async () => {
  statusEl.textContent = '';
  btnDl.disabled = true;
  showSpinner();
  await waitNextFrame();
  try {
    outText = await generatePDB();
    const N = Math.max(1, Math.min(4, parseInt(numLayersEl.value||"1")));
    draw3D(outText, N);
    btnDl.disabled = false;
  } catch(e) {
    statusEl.textContent = "Error";
    hideSpinner();
  }
});
document.getElementById("downloadBtn").addEventListener("click", () => {
  if (!outText) return;
  const na = (naTypeEl?.value || 'DNA').toUpperCase();
  const topology = topologyEl?.value || 'parallel';
  const N = Math.max(1, Math.min(4, parseInt(numLayersEl.value || "1")));
  const hand = globalHandEl.value || 'right';
  const fname = `G4_${na}_${N}layers_${hand}_${topology}.pdb`;
  const blob = new Blob([outText], { type: "chemical/x-pdb" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = fname;
  document.body.appendChild(a); a.click(); a.remove();
  URL.revokeObjectURL(url);
});